#!/usr/bin/env python3
"""Find x86 source of the self-calling align wrapper pattern."""
import pefile, capstone, re, struct

pe = pefile.PE(r"C:\Users\win2000\Downloads\(ROLL-UP1)Windows2000-KB891861-v2-x86-ENU\cmd.exe")
base = pe.OPTIONAL_HEADER.ImageBase

# .text section
text_rva = 0x1000
text_size = 0x1AE00
text_data = pe.get_data(text_rva, text_size)

md32 = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)

# The self-calling wrapper's body starts with:
# and dword ptr [rbp-8], 0  ->  83 65 F8 00
# In x86 this would be: and dword ptr [ebp-8], 0 -> 83 65 F8 00
pat_and = bytes([0x83, 0x65, 0xF8, 0x00])

print("=== Searching for 'and [ebp-8], 0' in x86 .text ===")
for m in re.finditer(pat_and, text_data):
    x86_rva = text_rva + m.start()
    x86_va = base + x86_rva
    # Disassemble around this
    ctx_start = max(0, m.start() - 16)
    ctx_end = min(len(text_data), m.start() + 40)
    ctx = text_data[ctx_start:ctx_end]
    print(f"x86 RVA 0x{x86_rva:X} (VA 0x{x86_va:X}):")
    for insn in md32.disasm(ctx, base + text_rva + ctx_start):
        marker = " <--" if insn.address == x86_va else ""
        print(f"  0x{insn.address:X}: {insn.mnemonic} {insn.op_str}{marker}")
    print()

# Also search for the extended body pattern starting from the x64 body:
# The x64 body at 0x4CF44 (after call+epilogue):
# 0x4CF49: and [rbp-8], 0        ; 83 65 F8 00
# 0x4CF4D: movabs rax, <global>  ; 48 B8 xx xx xx xx xx xx xx xx
# 0x4CF57: mov byte [rax], 1     ; C6 00 01
# 0x4CF5A: lea rax, [rbp-0x40]   ; 48 8D 45 C0
# 0x4CF5E: movabs r11, <global>  ; 49 BB xx xx xx xx xx xx xx xx
# 0x4CF68: mov [r11], eax        ; 41 89 03
# 0x4CF6B: lea rax, [rbp-0x40]   ; 48 8D 45 C0
# ...
# This is clearly a translated function body. The self-call is in the WRAPPER, not the body.
# The wrapper is generated by the translator.

# Let me check: is the wrapper at 0x4CF32 a separate entity, and the body at 0x4CF44
# is the actual translated function? Let me check the x64 binary more carefully.
print("\n=== Checking x64 binary structure around 0x4CF32 ===")
pe64 = pefile.PE("build_univ337/cmd_pure.exe")
rva = 0x4CF32
data64 = pe64.get_data(rva, 0x80)
md64 = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
for insn in md64.disasm(data64, 0x80000000 + rva):
    print(f"0x{insn.address:X}: {insn.mnemonic} {insn.op_str}")

# The wrapper pattern:
# 0x8004CF32: push r13          ; prologue
# 0x8004CF34: mov r13, rsp
# 0x8004CF37: sub rsp, 0x20
# 0x8004CF3B: and rsp, -0x10
# 0x8004CF3F: call 0x8004cf32   ; <-- CALLS THE PROLOGUE (WRONG!)
# 0x8004CF44: mov rsp, r13      ; epilogue
# 0x8004CF47: pop r13
# 0x8004CF49: and [rbp-8], 0    ; <-- actual function body starts here
# 
# So the call at 0x4CF3F should target 0x4CF49 (the body), not 0x4CF32 (the wrapper).
# The correct rel32 would be: 0x4CF49 - 0x4CF44 = 5
# But actual rel32 = 0xFFFFFFEE = -18, so target = 0x4CF44 + (-18) = 0x4CF32

# The issue: rel32 is off by 23 bytes. It should be +5, but it's -18.
# 5 - (-18) = 23 = 0x17
# This is exactly the length of the wrapper prologue (13) + call (5) + epilogue (5) = 23?
# Wait: prologue = 13 bytes (push r13(2) + mov r13,rsp(3) + sub rsp,0x20(4) + and rsp,-0x10(4))
# call = 5 bytes
# epilogue = 5 bytes (mov rsp,r13(3) + pop r13(2))
# Total = 23 bytes

# So the call is targeting 23 bytes BEFORE where it should be targeting!
# This suggests the call was originally emitted targeting the body, but then some
# post-processing step shifted it by -23 bytes, pointing it at the wrapper prologue.
