#!/usr/bin/env python3
"""Lift the Win2000 SSDT table out of legacy x86_x64.py into the package.

The rows are copied verbatim so the extracted module stays byte-for-byte
faithful to the numbers harvested from the real ntdll.dll.
"""

from __future__ import annotations

import io
import pathlib
import re

LEGACY = pathlib.Path('x86_x64.py')
TARGET = pathlib.Path('x86x64/syscall/table_data.py')

HEADER = '''"""Win2000 SSDT data, extracted from a real NT 5.0.2195 ntdll.dll.

Generated by ``tools/gen_syscall_data.py`` from the legacy ``x86_x64.py``
table; do not hand-edit the rows.  Each entry is
``(win2000_nr, win10_x64_nr, n_args, name)`` where ``n_args`` is the stub's
RET immediate divided by four, and a ``win10_x64_nr`` of 0 means no published
Win10 x64 equivalent has been mapped yet.
"""

from __future__ import annotations

from typing import List, Tuple

#: (win2000_nr, win10_x64_nr, n_args, name)
WIN2000_SYSCALL_TABLE: List[Tuple[int, int, int, str]] = [
'''


def main() -> int:
    text = LEGACY.read_text(encoding='utf-8', errors='replace').splitlines()

    start = next(i for i, line in enumerate(text)
                 if line.startswith('WIN2000_SYSCALL_TABLE'))
    end = next(i for i in range(start + 1, len(text)) if text[i].rstrip() == ']')
    rows = text[start + 1:end]

    count = sum(1 for line in rows if line.strip().startswith('(0x'))
    if count < 200:
        raise SystemExit(f'only found {count} rows -- refusing to write')

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    with io.open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(HEADER)
        fh.write('\n'.join(rows).rstrip() + '\n')
        fh.write(']\n')

    print(f'wrote {TARGET} with {count} syscall rows')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
